name: "Nitro Fusion Validate"
description: "Validates GraphQL source schemas against the Nitro registry"
author: "ChilliCream"
branding:
  icon: "check-circle"
  color: "purple"

inputs:
  stage:
    description: "The name of the stage"
    required: true
  api-id:
    description: "The ID of the API"
    required: true
  api-key:
    description: "API key for authentication"
    required: true
    secret: true
  source-schema-files:
    description: "Paths to source schema files (.graphqls) or directories containing source schema files"
    required: true
  cloud-url:
    description: "The URL of the Nitro registry"
    required: false

runs:
  using: "node20"
  main: "dist/index.js"
